### ISSUE TITLE
[talk/kata suggestion] Binary kata before benchmarking talk

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#3]
My suggestion is to do this 
https://github.com/elixir-berlin/kata-binary
and this time as the first thing to warm people and their fingers up for the Benchmarking talk

**Comment by duksis** [comment]
@PragTob anything against giving the talk after this?

**Comment by PragTob** [comment]
@duksis no, from a narrative perspective it'd just be good for me to include a related benchmark but I don't think I'll have the time to do this :) Plus if it takes longer I might have to cut the talk a bit shorter (original was ~50 mins, but I'm flexible with time and already cut a bit so that I'm guessing ~30-40)

**Comment by duksis** [comment]
@PragTob ok talk first code afterwards - the kata is can be pretty flexible when it comes to time.

**Comment by PragTob** [comment]
@duksis we can also do the code first, I don't have any strong opinions would just have liked to know a bit more in advance :) You make the call. See you tomorrow! :)
