### ISSUE TITLE
Talks for February meetup

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#5]
* [x]  "A primer on writing distributed databases" by @muaazsaleem 
* [ ] open slot
* [ ] open slot

Any talk ideas proposals welcome :)

**Comment by muaazsaleem** [comment]
Hi @duksis, since we don't have a talk yet, maybe I could do a talk called "A primer on writing distributed databases".

I haven't given this talk before and it lands in the "cool thing for fun" category. The talk will cover the various parts and choices that make up a distributed database. How tools provided by the Erlang VM make it easier to implement some of these parts.

**Comment by duksis** [comment]
Hi @muaazsaleem that sounds great! I'll update the meetup group and am looking forward to it.
The meetup is a pretty good place where to give a talk the first time :)

**Comment by muaazsaleem** [comment]
Thanks @duksis!
