### ISSUE TITLE
Location/Host for May

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/planning#8]
Host needed for May.

Please comment here if your company would be able to host us in May

**Comment by slashmili** [comment]
cc @klappradla

**Comment by boddhisattva** [comment]
Hello everyone,

Greetings from Bangalore, India. My name is Mohnish, a programmer with a Ruby background who is currently learning Elixir in his spare time and I'm also one of the co-organizers of the [Bangalore Ruby User Group meetups](https://www.meetup.com/Bangalore-Ruby-Users-Group/). I'll be in Germany between Apr 28th - May 14th and I'd like to propose that we could possibly solve an Exercism Elixir kata on the day of the meetup.

In the past, I had an opportunity to facilitate a hands on ruby meetup where people(in pairs of someone with more experience teaming up with someone with lesser experience) solved an exercism kata(which was only revealed on the day of the meetup to keep it fair). I blogged about my learnings from that experience [here](https://medium.com/@mohnishgj/learnings-from-facilitating-a-ruby-meetup-where-people-solved-an-exercism-kata-via-pair-programming-39c78113b86b) and Katrina Owen also made a mention of one of my tweets that spoke about this blog as part of the [news letter that speaks about how Exercism is being used in face-to-face interactions](http://tinyletter.com/exercism/letters/exercism-in-the-wild-how-is-exercism-being-used-in-face-to-face-interactions). This was something different than the usual talks that we do in ruby meetups in Bangalore, but overall it was well received because people learnt so many new things from the different approaches of solving a given problem.

Also, turns out there are other meetup groups like [Belfast FP](https://www.meetup.com/BelfastFP/)(Ireland based) that do kata hack nights as part of their meetups :).

To make it more fun and interesting, I propose that we could try solving this using [Mob Programming](https://en.wikipedia.org/wiki/Mob_programming) instead of pair programming. To get an overview of how things work the Mob Programming way I'd highly recommend you watch this [3 minute photographic guide to mob Programming](http://codecoupled.org/2015/10/30/a-journeymans-photographic-guide-to-mob-programming/) by [Lennart Friden](https://twitter.com/devlcsc?lang=en). For a more detailed intro to Mob Programming you could consider watching [this video](https://www.youtube.com/watch?v=8cy64qkgTyI) by [Woody Zuill](https://twitter.com/WoodyZuill) who has authored a book on Mob Programming. 

The prerequisites required for the meetup can be found in the agenda section of the below links and we could possibly use the same(with appropriate tweaks wherever required) for the May Berlin Elixir Meetup page [here](https://www.meetup.com/Elixir-Berlin/events/237370112/)  -
1. [April 2016 BRUG Meetup - Solving an Exercism Ruby Kata via pair programming](https://www.meetup.com/Bangalore-Ruby-Users-Group/events/230312848/?eventId=230312848)
2. [April 2017 BRUG Meetup - Solving an Exercism Ruby kata via Mob Programming](https://www.meetup.com/Bangalore-Ruby-Users-Group/events/239178217/)
Please note, we weren't able to do the April 2017 meetup on Mob programming as we had an unexpected low turnout even though many people had RSVped for the event(this was mostly because we had a long weekend around the day of the meetup. You'd find that meetups in India mostly happen in the weekends to my best knowledge). This way my experience of doing this the Mob programming way is relatively lesser but I've definitely thought through how we could do this if this is still a possibility you all would like to discuss further. 

Also, if we're planning to go ahead with this idea, we'd need a host that could accommodate us accordingly because for instance when doing things using Mob Programming we'd ideally require a projector for each team of 5 people working on an exercise as they'll be referring to one screen projecting the code at a given point in time. There are some workarounds to this that I've thought of in case projectors aren't available but happy to share more details if you all would like to discuss this further.

Please feel free to let me know if you have any questions around the proposed idea, I'll try to answer them to my best ability. Thanks.

**Comment by slashmili** [comment]
@boddhisattva Hey! Looks great.

To make the the discussion faster, could you join the elixir slack in #berlin channel? then we can discuss it there.

**Comment by boddhisattva** [comment]
Hi @slashmili, thanks for getting back to me on this. Glad to know you'd like to discuss this further. I'm actually already a member of the #berlin channel on elixir slack. You could find me there with the username `@mohnish`. Can you please share the username by which you go by in that group?

**Comment by slashmili** [comment]
@barsukov I remember you mentioned Qixxit would like to host us on May. Is the offer still on the table?

**Comment by barsukov** [comment]
@slashmili Currently our hr and me are sick and I could not 100% answer the question for May. I think we do not handle it in this month. For that reason, to not blocking you I would like to postpone Elixir meetup in Qixxit for May. 
Keep in touch.

**Comment by duksis** [comment]
@jonasschmidt would you know if Wooga could host us for 11th of May?

**Comment by dczombera** [comment]
Even though I really like new ideas and approaches, this kind of idea would be much better suited for an event that starts earlier and is carried out during the weekend. I guess a lot of ppl work as programmers, so coming up with interesting solutions to a problem after ~ 8 hours of coding is not that easy.

**Comment by duksis** [comment]
my experience show that @dczombera is right

**Comment by boddhisattva** [comment]
@dczombera Sure, when we had done a similar event as part of BRUG we had done this on a weekend(meetups in India are usually on weekends to my best knowledge). I can understand that it may not be that easy to come up with interesting solutions after 8 hours of office work. Please feel free to plan this some other time as discussed in the #berlin channel on the elixir lang slack group and if I could be of any help please feel free to get in touch. I'll be more than happy to share my two cents from an experience of doing something similar in the past.

**Comment by duksis** [comment]
Location for May will be @Bitcrowd thanks to @xhr15
